### ISSUE TITLE
There will be some files missing when you patch file 8c5f30bb2bb274f67d6e15f129be67

### ISSUE THREAD

**Issue by mikuyourworld** [HybridEidolon/pso2-modpatcher#2]
The file 8c5f30bb2bb274f67d6e15f129be67 which is in pso2_bin\data\win32reboot\e7

When I patched it, there will be 64 files which are in the group 2 will be missing in the patched one.

The original one should have 111 files in the group 2, but the patched one only have 47 files in the group 2.

**Comment by mikuyourworld** [comment]
I tried to patch it using different files, will get the same result.
So if you want to test, you can use any files to patch it I think.

**Comment by HybridEidolon** [comment]
Apologies for the late response. Aida pinged me on Discord with the issue.

For now I am just going to turn off recompression with Oodle. It'll inflate the installation size a bit more for translation patches, but the short-term solution requires linking to the oodle dll found in other games, and neither I nor the Tweaker can redistribute that dll ourselves.

I'll leave compression functionality open in the upstream library for now, but that oodle lib has been a headache in more ways than one. I'll leave this issue open for whenever I or somebody else manages to write a new oodle library in Rust, lol

**Comment by HybridEidolon** [comment]
Disabled compression in b472c03. That ice file should repack correctly now, although without compression.

**Comment by mikuyourworld** [comment]
> Apologies for the late response. Aida pinged me on Discord with the issue.
> 
> For now I am just going to turn off recompression with Oodle. It'll inflate the installation size a bit more for translation patches, but the short-term solution requires linking to the oodle dll found in other games, and neither I nor the Tweaker can redistribute that dll ourselves.
> 
> I'll leave compression functionality open in the upstream library for now, but that oodle lib has been a headache in more ways than one. I'll leave this issue open for whenever I or somebody else manages to write a new oodle library in Rust, lol

Thank you for your kind reply.
The modpatcher works correctly now.
